minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "TEST"
title_separator          : "-"
name                     : "GOHDONG"
description              : "An amazing website."
url                      : "gohdong.github.io"
baseurl                  : ""
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
